server.port=8080
spring.application.name=pbft
server.servlet.context-path=/api

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=admin
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=false          


#SHA 256 is the hash function 
#RSA is the assymetric encryption technique

#Sender:
#1. Message ---[Hash function]---> Original Digest
#2. Original Digest ---[Private key]---> Signature
#3. Send <Message, Signature>

#Receiver:
#1. Message ---[Hash function]---> Digest
#2. Signature ---[Public key]---> Original Digest
#3. If Digest == Original Digest, <Message, Signature> is valid
